# Generated by Django 5.2.17 on 2026-09-27 21:42

import django.db.models.deletion
from django.db import migrations, models
import uuid

class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('user_id', models.UUIDField(primary_key=True, default=uuid.uuid4, editable=False)),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(unique=True, max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('product_id', models.UUIDField(primary_key=True, default=uuid.uuid4, editable=False)),
                ('name', models.CharField(max_length=200)),
                ('category', models.CharField(max_length=100)),
                ('price', models.DecimalField(max_digits=10, decimal_places=2)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('review_id', models.UUIDField(primary_key=True, default=uuid.uuid4, editable=False)),
                ('review_text', models.TextField()),
                ('rating', models.IntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.User')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.Product')),
            ],
        ),
        migrations.CreateModel(
            name='ReviewImage',
            fields=[
                ('image_id', models.UUIDField(primary_key=True, default=uuid.uuid4, editable=False)),
                ('image_url', models.CharField(max_length=255)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('review', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.Review')),
            ],
        ),
        migrations.CreateModel(
            name='SentimentAnalysis',
            fields=[
                ('analysis_id', models.UUIDField(primary_key=True, default=uuid.uuid4, editable=False)),
                ('text_sentiment', models.CharField(max_length=20)),
                ('image_sentiment', models.CharField(max_length=20)),
                ('fusion_sentiment', models.CharField(max_length=20)),
                ('confidence_score', models.FloatField()),
                ('analyzed_at', models.DateTimeField(auto_now_add=True)),
                ('review', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='app.Review')),
            ],
        ),
        migrations.CreateModel(
            name='ModelLog',
            fields=[
                ('log_id', models.UUIDField(primary_key=True, default=uuid.uuid4, editable=False)),
                ('model_used', models.CharField(max_length=50)),
                ('execution_time', models.FloatField()),
                ('status', models.CharField(max_length=20)),
                ('analysis', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.SentimentAnalysis')),
            ],
        ),
    ]
